name: Latest content via JSON
on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:
    inputs:
      section:
        description: "Which section to update?"
        required: true
        default: "all"
        type: choice
        options: [all, blog, writeups, projects]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch index.json
        run: |
          FEED_URL="https://dhanraj.pages.dev/index.json"
          curl -sSL "$FEED_URL" -o /tmp/index.json

      - name: Build markdown blocks
        run: |
          # Normalize JSON: handle JSON Feed (.items) or PaperMod array
          jq 'if type=="object" and has("items") then .items else . end' /tmp/index.json > /tmp/items.json

          mklist () {
            # Generic list for blog/projects
            local path="$1" limit="$2"
            jq -r --arg path "$path" --argjson limit "$limit" '
              [ .[] 
                | select((.permalink // .url) | tostring | contains($path))
                | {title: (.title // .name),
                   link:  (.permalink // .url)
                  }
              ]
              | .[0:$limit]
              | map("* [\(.title)](\(.link))")
              | join("\n")
            ' /tmp/items.json
          }

          mklist_writeups () {
            # WRITEUPS: keep latest-first from feed, dedupe without sorting
            local path="$1" limit="$2"
            jq -r --arg path "$path" --argjson limit "$limit" '
              reduce ( .[] 
                | select((.permalink // .url) | tostring | contains($path))
                | { slug: ((.permalink // .url) | capture(".*/writeups/(?<slug>[^/]+)/") | .slug),
                    link: ((.permalink // .url) | capture("(?<link>.*?/writeups/[^/]+)/") | .link)
                  }
              ) as $item ( []; 
                if any(.slug == $item.slug) 
                then . 
                else . + [$item] 
                end
              )
              | .[0:$limit]
              | map("* [\(.slug)](\(.link)/)")
              | join("\n")
            ' /tmp/items.json
          }

          if [ "${{ github.event.inputs.section }}" = "all" ] || [ "${{ github.event.inputs.section }}" = "blog" ]; then
            mklist "/blog/" 10 > /tmp/blog.md
          fi
          if [ "${{ github.event.inputs.section }}" = "all" ] || [ "${{ github.event.inputs.section }}" = "writeups" ]; then
            mklist_writeups "/writeups/" 20 > /tmp/writeups.md
          fi
          if [ "${{ github.event.inputs.section }}" = "all" ] || [ "${{ github.event.inputs.section }}" = "projects" ]; then
            mklist "/projects/" 10 > /tmp/projects.md
          fi

      - name: Inject into README
        run: |
          inject () {
            local tag="$1" file="$2"
            awk -v tag="$tag" -v repl="$(sed 's/[&/\]/\\&/g' "$file")" '
              BEGIN{start="<!-- " tag ":START -->"; end="<!-- " tag ":END -->"}
              { if ($0==start){print; print repl; skip=1; next}
                if ($0==end){skip=0}
                if (!skip) print
              }' README.md > README.new && mv README.new README.md
          }

          [ -f /tmp/blog.md ] && inject "BLOG" /tmp/blog.md
          [ -f /tmp/writeups.md ] && inject "WRITEUPS" /tmp/writeups.md
          [ -f /tmp/projects.md ] && inject "PROJECTS" /tmp/projects.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): update ${{ github.event.inputs.section || 'all' }} from index.json"
