name: Latest content via JSON
on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:
    inputs:
      section:
        description: "Which section to update?"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - blog
          - writeups
          - projects

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch index.json
        run: |
          FEED_URL="https://dhanraj.pages.dev/index.json"
          curl -sSL "$FEED_URL" -o /tmp/index.json

      - name: Build markdown blocks
        run: |
          # Normalize JSON
          jq 'if type=="object" and has("items") then .items else . end' /tmp/index.json > /tmp/items.json

          mklist () {
            local path="$1" limit="$2"
            jq -r --arg path "$path" --argjson limit "$limit" '
              [ .[] 
                | select((.permalink // .url) | tostring | contains($path))
                | {title: (.title // .name),
                   link:  (.permalink // .url),
                   date:  (.date_published // .date // .publishDate // .dateFormatted // .lastmod // "")
                  }
              ]
              | sort_by(.date) | reverse | .[0:$limit]
              | map("* [\(.title)](\(.link))")
              | join("\n")
            ' /tmp/items.json
          }

          mklist_writeups () {
            local path="$1" limit="$2"
            jq -r --arg path "$path" --argjson limit "$limit" '
              [ .[]
                | select((.permalink // .url) | tostring | contains($path))
                | .permalink // .url
                | capture(".*/writeups/(?<slug>[^/]+)/")
                | .slug
              ]
              | unique
              | .[0:$limit]
              | map("* \(. )")
              | join("\n")
            ' /tmp/items.json
          }

          if [ "${{ github.event.inputs.section }}" = "all" ] || [ "${{ github.event.inputs.section }}" = "blog" ]; then
            mklist "/blog/" 10 > /tmp/blog.md
          fi
          if [ "${{ github.event.inputs.section }}" = "all" ] || [ "${{ github.event.inputs.section }}" = "writeups" ]; then
            mklist_writeups "/writeups/" 10 > /tmp/writeups.md
          fi
          if [ "${{ github.event.inputs.section }}" = "all" ] || [ "${{ github.event.inputs.section }}" = "projects" ]; then
            mklist "/projects/" 10 > /tmp/projects.md
          fi

      - name: Inject into README
        run: |
          inject () {
            local tag="$1" file="$2"
            awk -v tag="$tag" -v repl="$(sed 's/[&/\]/\\&/g' "$file")" '
              BEGIN{start="<!-- " tag ":START -->"; end="<!-- " tag ":END -->"}
              { if ($0==start){print; print repl; skip=1; next}
                if ($0==end){skip=0}
                if (!skip) print
              }' README.md > README.new && mv README.new README.md
          }

          if [ -f /tmp/blog.md ]; then
            inject "BLOG" /tmp/blog.md
          fi
          if [ -f /tmp/writeups.md ]; then
            inject "WRITEUPS" /tmp/writeups.md
          fi
          if [ -f /tmp/projects.md ]; then
            inject "PROJECTS" /tmp/projects.md
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): update ${{ github.event.inputs.section }} from index.json"
